# Generated by Django 3.1.2 on 2020-11-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_city_travelpost'),
        ('main_app', '0002_auto_20201102_1745'),
        ('main_app', '0002_auto_20201102_1744'),
    ]

    operations = [
    ]
