# Generated by Django 3.1.3 on 2020-11-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_merge_20201102_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpost',
            name='likes',
            field=models.IntegerField(),
        ),
    ]
