# Generated by Django 3.1.2 on 2020-11-02 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201102_1937'),
        ('main_app', '0004_merge_20201102_2031'),
        ('main_app', '0004_merge_20201102_1933'),
    ]

    operations = [
    ]
