# Generated by Django 3.1.2 on 2020-11-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_merge_20201102_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
