# Generated by Django 3.1.2 on 2020-11-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20201102_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpost',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
