# Generated by Django 3.1.3 on 2020-11-03 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201102_2158'),
        ('main_app', '0008_auto_20201102_2327'),
        ('main_app', '0006_auto_20201102_2346'),
    ]

    operations = [
    ]
