# Generated by Django 3.1.2 on 2020-11-03 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20201102_2327'),
        ('main_app', '0006_auto_20201102_2346'),
    ]

    operations = [
    ]
