# Generated by Django 3.1.3 on 2020-11-03 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_merge_20201103_0024'),
        ('main_app', '0009_merge_20201103_0018'),
    ]

    operations = [
    ]
