# Generated by Django 3.1.2 on 2020-11-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_merge_20201103_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpost',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
