# Generated by Django 3.1.2 on 2020-11-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_merge_20201102_1940'),
        ('main_app', '0010_merge_20201103_0052'),
        ('main_app', '0011_auto_20201103_0506'),
    ]

    operations = [
    ]
