# Generated by Django 3.1.3 on 2020-11-04 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_merge_20201104_1712'),
        ('main_app', '0012_merge_20201104_1720'),
    ]

    operations = [
    ]
