# Generated by Django 3.1.3 on 2020-11-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_remove_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='https://picsum.photos/200/300', null=True, upload_to=''),
        ),
    ]
