# Generated by Django 3.1.2 on 2020-11-06 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_like_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='test',
        ),
    ]
