# Generated by Django 3.1.3 on 2020-11-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_auto_20201105_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/images/beach.png', null=True, upload_to=''),
        ),
    ]
