# Generated by Django 3.1.3 on 2020-11-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20201105_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images/beach.png', upload_to=''),
        ),
    ]
