# Generated by Django 3.1.3 on 2020-11-05 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_auto_20201105_2205'),
        ('main_app', '0019_like'),
    ]

    operations = [
    ]
